### ISSUE TITLE
Cast error 

### ISSUE THREAD

**Issue by SebAubin** [gskinnerTeam/flutter-context-menu#9]
Hi, some times I get this error while trying to show the menu:

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
type 'Null' is not a subtype of type '_InheritedContextMenu' in type cast

When the exception was thrown, this was the stack: 
#0      ContextMenuOverlay.of (package:context_menus/src/context_menu_overlay.dart:43:76)
#1      ContextMenuExtensions.contextMenuOverlay (package:context_menus/context_menus.dart:20:72)
#2      ContextMenuRegion.build.showMenu (package:context_menus/src/context_menu_region.dart:19:15)
#3      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:619:71)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:619:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#24     _invoke1 (dart:ui/hooks.dart:170:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onSecondaryTap"
Recognizer: TapGestureRecognizer#e9365
  debugOwner: GestureDetector
  state: ready
```

My code:
```
child: ContextMenuRegion(
        contextMenu: GenericContextMenu(
          buttonConfigs: [
            ContextMenuButtonConfig(
              "Button 1",
              onPressed: () => _copyCode(),
            ),
 ContextMenuButtonConfig(
              "Button 2",
              onPressed: () => _copyCode(),
            ),
 ContextMenuButtonConfig(
              "Button 3",
              onPressed: () => _copyCode(),
            ),
          ],
        ),
        child: ListTile(...))
```

Is there a known issue?

**Comment by esDotDev** [comment]
This is caused by using a MenuRegion without a MenuOverlay above it in the tree. In v1.1.1 I've added a better error message to that effect.
